export const PERMISSIONS = {
  USER: {
    READ: "USER_READ",
    CREATE: "USER_CREATE",
    DELETE: "USER_DELETE",
    UPDATE: "USER_UPDATE",
  },
  ROLE: {
    READ: "ROLE_READ",
    CREATE: "ROLE_CREATE",
    DELETE: "ROLE_DELETE",
    UPDATE: "ROLE_UPDATE",
  },
  PERMISSION: {
    READ: "PERMISSION_READ",
    CREATE: "PERMISSION_CREATE",
    DELETE: "PERMISSION_DELETE",
    UPDATE: "PERMISSION_UPDATE",
  },
  FRIEND: {
    READ: "FRIEND_READ",
    CREATE: "FRIEND_CREATE",
    DELETE: "FRIEND_DELETE",
    UPDATE: "FRIEND_UPDATE",
  },
  MESSAGE: {
    READ: "MESSAGE_READ",
    CREATE: "MESSAGE_CREATE",
    DELETE: "MESSAGE_DELETE",
    UPDATE: "MESSAGE_UPDATE",
  }
} as const;
